version: '3'
tasks:
  init:
    run: once
    desc: Initializes the repo
    cmds:
      - git submodule init
      - git submodule update
  push-submodules:
    run: once
    desc: Pushes submodules
    cmds:
      - ./scripts/push-submodules.sh
      - git reset
      - git add "kirito"
      - git add "roxxy"
      - cmd: git commit -m "[TASKFILE] update submodules"
        ignore_error: true
      - git push
