version: '3'
tasks:
  init:
    run: once
    desc: Initializes the repo
    cmds:
      - git submodule init
      - git submodule update
      - cd roxxy && git checkout master && cd ..
      - cd kirito && git checkout master && cd ..
  push-submodules:
    run: once
    desc: Pushes submodules
    cmds:
      - ./scripts/push-submodule.sh ./kirito
      - ./scripts/push-submodule.sh ./roxxy
      - git reset
      - git add "kirito"
      - git add "roxxy"
      - cmd: git commit -m "[TASKFILE] update submodules"
        ignore_error: true
      - git push
